config/routes.rb
# == Route Map
#
#           Prefix Verb   URI Pattern                             Controller#Action
#             root GET    /                                       static_pages#home
#       categories GET    /products/categories(.:format)          categories#index
#                  POST   /products/categories(.:format)          categories#create
#     new_category GET    /products/categories/new(.:format)      categories#new
#    edit_category GET    /products/categories/:id/edit(.:format) categories#edit
#         category PATCH  /products/categories/:id(.:format)      categories#update
#                  PUT    /products/categories/:id(.:format)      categories#update
#                  DELETE /products/categories/:id(.:format)      categories#destroy
#         products GET    /products(.:format)                     products#index
#                  POST   /products(.:format)                     products#create
#      new_product GET    /products/new(.:format)                 products#new
#     edit_product GET    /products/:id/edit(.:format)            products#edit
#          product GET    /products/:id(.:format)                 products#show
#                  PATCH  /products/:id(.:format)                 products#update
#                  PUT    /products/:id(.:format)                 products#update
#                  DELETE /products/:id(.:format)                 products#destroy
#   ethnic_dresses GET    /ethnic-dresses(.:format)               products#category_index {:category=>"Ethnic Dresses"}
#  wedding_dresses GET    /wedding-dresses(.:format)              products#category_index {:category=>"Wedding Dresses"}
#  western_dresses GET    /western-dresses(.:format)              products#category_index {:category=>"Western Dresses"}
#            login GET    /login(.:format)                        authentication#login
#                  GET    /auth/:provider/callback(.:format)      authentication#oauth_callback
#     auth_failure GET    /auth/failure(.:format)                 redirect(301, /)
#      add_to_cart POST   /add-to-cart(.:format)                  orders#add_to_cart
# remove_from_cart GET    /remove-from-cart(.:format)             orders#remove_from_cart
#        show_cart GET    /shopping-cart(.:format)                orders#show_cart
#    cart_checkout GET    /cart/checkout(.:format)                orders#cart_checkout
#      place_order POST   /cart/checkout(.:format)                orders#place_order
#        thank_you GET    /thank_you(.:format)                    orders#thank_you
#         about_us GET    /about_us(.:format)                     static_pages#about_us
#            admin GET    /admin(.:format)                        admin#dashboard
#

Rails.application.routes.draw do

  root 'static_pages#home'

  resources :products do
    collection do
      resources :categories, except: :show
    end
  end

  get 'ethnic-dresses', to: 'products#category_index', category: 'Ethnic Dresses'
  get 'wedding-dresses', to: 'products#category_index', category: 'Wedding Dresses'
  get 'western-dresses', to: 'products#category_index', category: 'Western Dresses'

  get 'login', to: 'authentication#login'
  get "/auth/:provider/callback", to: 'authentication#oauth_callback'
  get 'auth/failure', to: redirect('/')

  post 'add-to-cart', to: 'orders#add_to_cart', as: :add_to_cart
  get 'remove-from-cart', to: 'orders#remove_from_cart', as: :remove_from_cart
  get 'shopping-cart', to: 'orders#show_cart', as: :show_cart
  get 'cart/checkout', to: 'orders#cart_checkout', as: :cart_checkout
  post 'cart/checkout', to: "orders#place_order", as: :place_order
  get 'thank_you', to: 'orders#thank_you'

  get 'about_us', to: 'static_pages#about_us'

  get 'admin', to: 'admin#dashboard'
end

app/views/admin/_orders_table.html.erb
<table class="table table-bordered table-hover table-striped">
  <thead>
    <th>Order Id</th>
    <th>Order Items</th>
    <th>Order Subtotal</th>
    <th>Order Total</th>
    <th>Order Status</th>
  </thead>
  <tbody>
    <% orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td>
          <% order.line_items.each do |line_item| %>
            <ul>
              <li><%= line_item.product.name %>, <%= line_item.price %></li>
            </ul>
          <% end %>
        </td>
        <td><%= order.subtotal %></td>
        <td><%= order.total %></td>
        <td><%= order.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/_orders_tabs.html.erb
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#processing" aria-controls="processing" role="tab" data-toggle="tab">Processing</a></li>
    <li role="presentation"><a href="#delivered" aria-controls="delivered" role="tab" data-toggle="tab">Delivered</a></li>
    <li role="presentation"><a href="#collected" aria-controls="collected" role="tab" data-toggle="tab">Collected</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="processing">
      <%= render 'orders_table', orders: @processing_orders %>
    </div>
    <div role="tabpanel" class="tab-pane" id="delivered">
      <%= render 'orders_table', orders: @delivered_orders %>
    </div>
    <div role="tabpanel" class="tab-pane" id="collected">
      <%= render 'orders_table', orders: @collected_orders %>
    </div>
  </div>

</div>

app/views/admin/dashboard.html.erb
<!DOCTYPE HTML>
<html>

<head>
  <title>Homepage - theBoomerang</title>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
  <meta name="description" content="TheBox">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="/css/bootstrap.css">
</head>

<body>
  <div class="row">
    <div class="col-sm-12 col-md-3">
      <ul class="list-group">
        <li class="list-group-item"><%= link_to 'Products', products_path %></li>
        <li class="list-group-item"><%= link_to 'Categories', categories_path %></li>
      </ul>
    </div>
    <div class="col-sm-12 col-md-9">
      <h2>Orders</h2>
      <%= render 'orders_tabs' %>
    </div>
  </div>

  <script src="/js/jquery.js"></script>
  <script src="/js/bootstrap.js"></script>
</body>

</html>