config/routes.rb
# == Route Map
#
#           Prefix Verb   URI Pattern                             Controller#Action
#             root GET    /                                       static_pages#home
#       categories GET    /products/categories(.:format)          categories#index
#                  POST   /products/categories(.:format)          categories#create
#     new_category GET    /products/categories/new(.:format)      categories#new
#    edit_category GET    /products/categories/:id/edit(.:format) categories#edit
#         category PATCH  /products/categories/:id(.:format)      categories#update
#                  PUT    /products/categories/:id(.:format)      categories#update
#                  DELETE /products/categories/:id(.:format)      categories#destroy
#         products GET    /products(.:format)                     products#index
#                  POST   /products(.:format)                     products#create
#      new_product GET    /products/new(.:format)                 products#new
#     edit_product GET    /products/:id/edit(.:format)            products#edit
#          product GET    /products/:id(.:format)                 products#show
#                  PATCH  /products/:id(.:format)                 products#update
#                  PUT    /products/:id(.:format)                 products#update
#                  DELETE /products/:id(.:format)                 products#destroy
#   ethnic_dresses GET    /ethnic-dresses(.:format)               products#category_index {:category=>"Ethnic Dresses"}
#  wedding_dresses GET    /wedding-dresses(.:format)              products#category_index {:category=>"Wedding Dresses"}
#  western_dresses GET    /western-dresses(.:format)              products#category_index {:category=>"Western Dresses"}
#            login GET    /login(.:format)                        authentication#login
#                  GET    /auth/:provider/callback(.:format)      authentication#oauth_callback
#     auth_failure GET    /auth/failure(.:format)                 redirect(301, /)
#      add_to_cart POST   /add-to-cart(.:format)                  orders#add_to_cart
# remove_from_cart GET    /remove-from-cart(.:format)             orders#remove_from_cart
#        show_cart GET    /shopping-cart(.:format)                orders#show_cart
#    cart_checkout GET    /cart/checkout(.:format)                orders#cart_checkout
#      place_order POST   /cart/checkout(.:format)                orders#place_order
#        thank_you GET    /thank_you(.:format)                    orders#thank_you
#         about_us GET    /about_us(.:format)                     static_pages#about_us
#            admin GET    /admin(.:format)                        admin#dashboard
#

Rails.application.routes.draw do

  root 'static_pages#home'

  resources :products do
    collection do
      resources :categories, except: :show
    end
  end

  get 'ethnic-dresses', to: 'products#category_index', category: 'Ethnic Dresses'
  get 'wedding-dresses', to: 'products#category_index', category: 'Wedding Dresses'
  get 'western-dresses', to: 'products#category_index', category: 'Western Dresses'

  get 'login', to: 'authentication#login'
  get "/auth/:provider/callback", to: 'authentication#oauth_callback'
  get 'auth/failure', to: redirect('/')

  post 'add-to-cart', to: 'orders#add_to_cart', as: :add_to_cart
  get 'remove-from-cart', to: 'orders#remove_from_cart', as: :remove_from_cart
  get 'shopping-cart', to: 'orders#show_cart', as: :show_cart
  get 'cart/checkout', to: 'orders#cart_checkout', as: :cart_checkout
  post 'cart/checkout', to: "orders#place_order", as: :place_order
  get 'thank_you', to: 'orders#thank_you'

  get 'about_us', to: 'static_pages#about_us'

  get 'admin', to: 'admin#dashboard'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  status        :string
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  delivery_date :date
#

class Order < ActiveRecord::Base

  has_many :line_items
  has_many :products, through: :line_items
  belongs_to :user
  has_one :order_shipping_address

  def add_item(item_attributes)
    if self.status == 'cart'
      item_attributes = HashWithIndifferentAccess.new(item_attributes)
      self.line_items.where(product_id: item_attributes[:product_id]).destroy_all
      return self.line_items.create(item_attributes)
    else
      return false
    end
  end

  def remove_item(line_item_id)
    self.line_items.where(id: line_item_id).destroy_all
  end

  def empty?
    return self.line_items.count == 0
  end

  def subtotal
    return self.line_items.map { |item| item.price }.sum
  end

  def shipping
    return 0 # free
  end

  def total
    self.subtotal + shipping
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def add_to_cart
    @cart = current_user.cart
    @cart.add_item(params[:cart])
    begin
      redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to(product_path(params[:cart][:product_id]))
    end
  end

  def remove_from_cart
    @cart = current_user.cart
    @cart.remove_item(params[:line_item_id])
    redirect_to show_cart_path
  end

  def show_cart
    @cart = current_user.cart
  end

  def cart_checkout
    @cart = current_user.cart
    @order_shipping_address = OrderShippingAddress.new(user: current_user, order: @cart)
  end

  def place_order
    @cart = current_user.cart
    if @cart.empty?
      redirect_to root_path
    else
      @order_shipping_address = OrderShippingAddress.new(order_params.merge(user: current_user, order: @cart))
      if @order_shipping_address.save
        @cart.status = "processing"
        @cart.save
        redirect_to thank_you_path
      else
        render :cart_checkout
      end
    end
  end

  def thank_you
    @order = current_user.orders.where(status: 'processing').last
    @order_shipping_address = @order.order_shipping_address
  end

  private
    def order_params
       params.require(:order).permit(:name, :email, :phone_number, :state, :city, :address, :zip)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/cart_checkout.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <title>theBoomerang-login</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <meta name="keywords" content="Template, html, premium, themeforest" />
    <meta name="description" content="TheBox - premium e-commerce template">
    <meta name="author" content="Tsoy">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='http://fonts.googleapis.com/css?family=Roboto:500,300,700,400italic,400' rel='stylesheet' type='text/css'>
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'> -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'> -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/font-awesome.css">
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="stylesheet" href="/css/mystyles.css">
    <link rel="stylesheet" href="/css/switcher.css" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/bright-turquoise.css" title="bright-turquoise" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/turkish-rose.css" title="turkish-rose" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/salem.css" title="salem" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/hippie-blue.css" title="hippie-blue" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/mandy.css" title="mandy" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/green-smoke.css" title="green-smoke" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/horizon.css" title="horizon" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/cerise.css" title="cerise" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/brick-red.css" title="brick-red" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/de-york.css" title="de-york" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/shamrock.css" title="shamrock" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/studio.css" title="studio" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/leather.css" title="leather" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/denim.css" title="denim" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="/css/schemes/scarlet.css" title="scarlet" media="all" />
</head>

<body>
    <div class="global-wrapper clearfix" id="global-wrapper">

      <nav class="navbar navbar-inverse navbar-main yamm" style="">
          <div class="container">
              <div class="navbar-header">
                  <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-nav-collapse" area_expanded="false"><span class="sr-only">Main Menu</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/" style="color: white">
                      The boomerang
                  </a>
              </div>
              <div class="collapse navbar-collapse" id="main-nav-collapse">


                  <ul class="nav navbar-nav navbar-right">

                      <li><a href="/western-dresses.html" data-effect="mfp-move-from-top">Western Dress</a>
                      </li>

                      <li><a href="/wedding-dresses.html" data-effect="mfp-move-from-top">Wedding Dress</a>
                      </li>

                      <li><a href="/login.html" data-effect="mfp-move-from-top">Sign In</a>
                      </li>


                      <li class="dropdown">
                          <a class="fa fa-shopping-cart" href="/shopping-cart.html"></a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>

      <div class="container">
            <header class="page-header">
                <h1 class="page-title">Checkout Order</h1>
            </header>
            <!-- <p class="checkout-login-text"></p> -->
            <div class="row row-col-gap" data-gutter="60">
                <div class="col-md-4">
                    <h3 class="widget-title">Order Info</h3>
                    <div class="box">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Days</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>
                              <% @cart.line_items.each do |line_item| %>
                                <tr>
                                    <td><%= line_item.product.name %></td>
                                    <td><%= line_item.days_to_rent %></td>
                                    <td><%= line_item.price %></td>
                                </tr>
                              <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-4">
                    <h3 class="widget-title">Billng Details</h3>
                    <%= form_for(@order_shipping_address, url: place_order_url, html: { id: 'place_order' }) do %>
                        <div class="form-group">
                            <label>First &amp; Last Name</label>
                            <input class="form-control" type="text" name="order[name]" value='<%= @order_shipping_address.name %>' />
                            <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:name).first %></p>
                        </div>
                        <div class="form-group">
                            <label>E-mail</label>
                            <input class="form-control" type="text" name="order[email]" value='<%= @order_shipping_address.email %>' />
                            <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:email).first %></p>
                        </div>
                        <div class="form-group">
                            <label>Phone Number</label>
                            <input class="form-control" type="text" name="order[phone_number]" value='<%= @order_shipping_address.phone_number %>' />
                            <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:phone_number).first %></p>
                        </div>
                        <div class="form-group">
                            <label>State</label>
                            <input class="form-control" type="text" name="order[state]" value='<%= @order_shipping_address.state %>' />
                            <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:state).first %></p>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>City</label>
                                    <input class="form-control" type="text" name="order[city]" value='<%= @order_shipping_address.city %>' />
                                    <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:city).first %></p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Zip/Postal</label>
                                    <input class="form-control" type="text" name="order[zip]" value='<%= @order_shipping_address.zip %>' />
                                    <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:zip).first %></p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input class="form-control" type="text" name="order[address]" value='<%= @order_shipping_address.address %>' />
                            <p style="color: red"><%= @order_shipping_address.errors.full_messages_for(:address).first %></p>
                        </div>
                    <% end %>
                </div>
                <div class="col-md-4">
                    <h3 class="widget-title">Payment</h3>
                    <p> Payment will be done by cash on delivery. </p>
                    <%= button_tag('Place Order', form: 'place_order', class: 'btn btn-primary') %>
                </div>
            </div>
        </div>

                <div class="gap gap-small"></div>


        <footer class="main-footer">
            <div class="container">
                <div class="row row-col-gap" data-gutter="60">
                    <div class="col-md-4">
                        <h4 class="widget-title-sm">TheBoomerang</h4>
                        <p>Tincidunt et scelerisque vulputate ultrices ante at eu risus tempor augue congue</p>
                        <ul class="main-footer-social-list">
                            <li>
                                <a class="fa fa-facebook" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-twitter" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-pinterest" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-instagram" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-google-plus" href="product-layout-3.html#"></a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-4">
                        <h4 class="widget-title-sm">Jobs</h4>
                        <form>

                            <input class="btn btn-primary" type="submit" value="We're hiring" />
                        </form>
                    </div>
                </div>

            </div>
        </footer>

    </div>
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap.js"></script>
    <script src="/js/icheck.js"></script>
    <script src="/js/ionrangeslider.js"></script>
    <script src="/js/jqzoom.js"></script>
    <script src="/js/card-payment.js"></script>
    <script src="/js/owl-carousel.js"></script>
    <script src="/js/magnific.js"></script>
    <script src="/js/custom.js"></script>


    <script src="/js/switcher.js"></script>



</body>

</html>

app/views/orders/show_cart.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <title>Shopping Cart</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <meta name="keywords" content="Template, html, premium, themeforest" />
    <meta name="description" content="TheBox - premium e-commerce template">
    <meta name="author" content="Tsoy">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='http://fonts.googleapis.com/css?family=Roboto:500,300,700,400italic,400' rel='stylesheet' type='text/css'>
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'> -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'> -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/font-awesome.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/mystyles.css">
    <link rel="stylesheet" href="css/switcher.css" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/bright-turquoise.css" title="bright-turquoise" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/turkish-rose.css" title="turkish-rose" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/salem.css" title="salem" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/hippie-blue.css" title="hippie-blue" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/mandy.css" title="mandy" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/green-smoke.css" title="green-smoke" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/horizon.css" title="horizon" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/cerise.css" title="cerise" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/brick-red.css" title="brick-red" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/de-york.css" title="de-york" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/shamrock.css" title="shamrock" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/studio.css" title="studio" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/leather.css" title="leather" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/denim.css" title="denim" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/scarlet.css" title="scarlet" media="all" />
</head>

<body>
    <div class="global-wrapper clearfix" id="global-wrapper">


      <nav class="navbar navbar-inverse navbar-main yamm" style="">
          <div class="container">
              <div class="navbar-header">
                  <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-nav-collapse" area_expanded="false"><span class="sr-only">Main Menu</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/" style="color: white">
                      The boomerang
                  </a>
              </div>
              <div class="collapse navbar-collapse" id="main-nav-collapse">


                  <ul class="nav navbar-nav navbar-right">

                      <li><a href="/western-dresses.html" data-effect="mfp-move-from-top">Western Dress</a>
                      </li>

                      <li><a href="/wedding-dresses.html" data-effect="mfp-move-from-top">Wedding Dress</a>
                      </li>

                      <li><a href="/login.html" data-effect="mfp-move-from-top">Sign In</a>
                      </li>


                      <li class="dropdown">
                          <a class="fa fa-shopping-cart" href="/shopping-cart.html"></a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>

        <div class="container">
            <header class="page-header">
                <h1 class="page-title">My Shopping Bag</h1>
            </header>
            <% if @cart.empty? %>
              <div class="row">
                <div class="col-md-10">
                  <h4>Your cart is empty.</h4>
                </div>
                <div class="gap"></div>
              </div>
            <% else %>
              <div class="row">
                  <div class="col-md-10">
                      <table class="table table table-shopping-cart">
                          <thead>
                              <tr>
                                  <th>Product</th>
                                  <th>Title</th>
                                  <th>Size</th>
                                  <th>Price</th>
                                  <th>Days to Rent</th>
                                  <th>Total</th>
                                  <th>Remove</th>
                              </tr>
                          </thead>
                          <tbody>
                              <% @cart.line_items.each do |line_item| %>
                                <tr>
                                    <td class="table-shopping-cart-img">
                                        <a href=<%= product_path(line_item.product_id) %>>
                                            <img src=<%= line_item.product.images[0].url %> />
                                        </a>
                                    </td>
                                    <td class="table-shopping-cart-title"><a href=<%= product_path(line_item.product_id) %>><%= line_item.product.name %></a>
                                    </td>
                                    <td><%= line_item.size %></td>
                                    <td><%= line_item.price %></td>
                                    <td><%= line_item.days_to_rent %></td>
                                    <td><%= line_item.price %></td>
                                    <td>
                                        <a class="fa fa-close table-shopping-remove" href=<%= remove_from_cart_path(line_item_id: line_item.id) %>></a>
                                    </td>
                                </tr>
                              <% end %>

                          </tbody>
                      </table>
                      <div class="gap gap-small"></div>
                  </div>
                  <div class="col-md-2">
                      <ul class="shopping-cart-total-list">
                          <li><span>Subtotal</span><span><%= @cart.subtotal %></span>
                          </li>
                          <li><span>Shipping</span><span>Free</span>
                          </li>
                          <li><span>Total</span><span><%= @cart.total %></span>
                          </li>
                      </ul><a class="btn btn-primary" href=<%= cart_checkout_path %>>Checkout</a>
                  </div>
              </div>
            <% end %>
            <ul class="list-inline">
                <li><a class="btn btn-default" href="/">Continue Shopping</a>
                </li>
            </ul>

        </div>

        <div class="gap"></div>


        <footer class="main-footer">
            <div class="container">
                <div class="row row-col-gap" data-gutter="60">
                    <div class="col-md-4">
                        <h4 class="widget-title-sm">TheBoomerang</h4>
                        <p>Tincidunt et scelerisque vulputate ultrices ante at eu risus tempor augue congue</p>
                        <ul class="main-footer-social-list">
                            <li>
                                <a class="fa fa-facebook" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-twitter" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-pinterest" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-instagram" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-google-plus" href="product-layout-3.html#"></a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-4">
                        <h4 class="widget-title-sm">Jobs</h4>
                        <form>

                            <input class="btn btn-primary" type="submit" value="We're hiring" />
                        </form>
                    </div>
                </div>

            </div>
        </footer>

    </div>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/icheck.js"></script>
    <script src="js/ionrangeslider.js"></script>
    <script src="js/jqzoom.js"></script>
    <script src="js/card-payment.js"></script>
    <script src="js/owl-carousel.js"></script>
    <script src="js/magnific.js"></script>
    <script src="js/custom.js"></script>


    <script src="js/switcher.js"></script>



</body>

</html>