config/routes.rb
# == Route Map
#
#           Prefix Verb   URI Pattern                             Controller#Action
#             root GET    /                                       static_pages#home
#       categories GET    /products/categories(.:format)          categories#index
#                  POST   /products/categories(.:format)          categories#create
#     new_category GET    /products/categories/new(.:format)      categories#new
#    edit_category GET    /products/categories/:id/edit(.:format) categories#edit
#         category PATCH  /products/categories/:id(.:format)      categories#update
#                  PUT    /products/categories/:id(.:format)      categories#update
#                  DELETE /products/categories/:id(.:format)      categories#destroy
#         products GET    /products(.:format)                     products#index
#                  POST   /products(.:format)                     products#create
#      new_product GET    /products/new(.:format)                 products#new
#     edit_product GET    /products/:id/edit(.:format)            products#edit
#          product GET    /products/:id(.:format)                 products#show
#                  PATCH  /products/:id(.:format)                 products#update
#                  PUT    /products/:id(.:format)                 products#update
#                  DELETE /products/:id(.:format)                 products#destroy
#   ethnic_dresses GET    /ethnic-dresses(.:format)               products#category_index {:category=>"Ethnic Dresses"}
#  wedding_dresses GET    /wedding-dresses(.:format)              products#category_index {:category=>"Wedding Dresses"}
#  western_dresses GET    /western-dresses(.:format)              products#category_index {:category=>"Western Dresses"}
#            login GET    /login(.:format)                        authentication#login
#                  GET    /auth/:provider/callback(.:format)      authentication#oauth_callback
#     auth_failure GET    /auth/failure(.:format)                 redirect(301, /)
#      add_to_cart POST   /add-to-cart(.:format)                  orders#add_to_cart
# remove_from_cart GET    /remove-from-cart(.:format)             orders#remove_from_cart
#        show_cart GET    /shopping-cart(.:format)                orders#show_cart
#    cart_checkout GET    /cart/checkout(.:format)                orders#cart_checkout
#      place_order POST   /cart/checkout(.:format)                orders#place_order
#        thank_you GET    /thank_you(.:format)                    orders#thank_you
#         about_us GET    /about_us(.:format)                     static_pages#about_us
#            admin GET    /admin(.:format)                        admin#dashboard
#

Rails.application.routes.draw do

  root 'static_pages#home'

  resources :products do
    collection do
      resources :categories, except: :show
    end
  end

  get 'ethnic-dresses', to: 'products#category_index', category: 'Ethnic Dresses'
  get 'wedding-dresses', to: 'products#category_index', category: 'Wedding Dresses'
  get 'western-dresses', to: 'products#category_index', category: 'Western Dresses'

  get 'login', to: 'authentication#login'
  get "/auth/:provider/callback", to: 'authentication#oauth_callback'
  get 'auth/failure', to: redirect('/')

  post 'add-to-cart', to: 'orders#add_to_cart', as: :add_to_cart
  get 'remove-from-cart', to: 'orders#remove_from_cart', as: :remove_from_cart
  get 'shopping-cart', to: 'orders#show_cart', as: :show_cart
  get 'cart/checkout', to: 'orders#cart_checkout', as: :cart_checkout
  post 'cart/checkout', to: "orders#place_order", as: :place_order
  get 'thank_you', to: 'orders#thank_you'

  get 'about_us', to: 'static_pages#about_us'

  get 'admin', to: 'admin#dashboard'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  name            :string
#  rent_price      :integer
#  actual_price    :integer
#  sizes_available :string           default([]), is an Array
#  description     :text
#  images          :json
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Product < ActiveRecord::Base

  mount_uploaders :images, ImageUploader

  SIZES = [ 'S', 'M', 'L', 'XL' ]

  has_many :product_categories, dependent: :destroy
  accepts_nested_attributes_for :product_categories
  has_many :categories, through: :product_categories
  has_many :line_items
  has_many :orders, through: :line_items

  validates_presence_of :name
  validates :rent_price, numericality: { greater_than: 0, integer: true }
  validates :actual_price, numericality: { greater_than: 0, integer: true }
  validate :at_least_one_size_is_available
  validate :valid_sizes_available_array
  validate :at_least_one_image

  private

    def at_least_one_size_is_available
      unless sizes_available.is_a?(Array) && sizes_available.length > 0
        errors.add(:sizes_available, 'at least one size must be available')
      end
    end

    def valid_sizes_available_array
      if sizes_available.detect{|s| !SIZES.include?(s)}
        errors.add(:sizes_available, :invalid)
      end
    end

    def at_least_one_image
      if self.images.empty?
        errors.add(:images, 'at least one image must be present')
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action -> { restrict_to('admin') }, except: [:index, :show, :category_index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'application'

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    render layout: false
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    params[:product][:sizes_available].delete("")
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /products/1
  def update
    params[:product][:sizes_available].delete("")
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
    end
  end

  def category_index
    @category = Category.where(name: params[:category]).take
    @products = @category.products
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :rent_price, :actual_price, :description, sizes_available: [], category_ids: [], images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/category_index.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <title>Product layout</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <meta name="keywords" content="Template, html, premium, themeforest" />
    <meta name="description" content="TheBox - premium e-commerce template">
    <meta name="author" content="Tsoy">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='http://fonts.googleapis.com/css?family=Roboto:500,300,700,400italic,400' rel='stylesheet' type='text/css'>
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'> -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'> -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/font-awesome.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/mystyles.css">
    <link rel="stylesheet" href="css/switcher.css" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/bright-turquoise.css" title="bright-turquoise" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/turkish-rose.css" title="turkish-rose" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/salem.css" title="salem" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/hippie-blue.css" title="hippie-blue" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/mandy.css" title="mandy" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/green-smoke.css" title="green-smoke" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/horizon.css" title="horizon" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/cerise.css" title="cerise" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/brick-red.css" title="brick-red" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/de-york.css" title="de-york" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/shamrock.css" title="shamrock" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/studio.css" title="studio" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/leather.css" title="leather" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/denim.css" title="denim" media="all" />
    <link rel="alternate stylesheet" type="text/css" href="css/schemes/scarlet.css" title="scarlet" media="all" />
</head>

<body>
    <div class="global-wrapper clearfix" id="global-wrapper">

      <nav class="navbar navbar-inverse navbar-main yamm" style="">
          <div class="container">
              <div class="navbar-header">
                  <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#main-nav-collapse" area_expanded="false"><span class="sr-only">Main Menu</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/" style="color: white">
                      The boomerang
                  </a>
              </div>
              <div class="collapse navbar-collapse" id="main-nav-collapse">


                  <ul class="nav navbar-nav navbar-right">

                      <li><a href="/western-dresses.html" data-effect="mfp-move-from-top">Western Dress</a>
                      </li>

                      <li><a href="/wedding-dresses.html" data-effect="mfp-move-from-top">Wedding Dress</a>
                      </li>

                      <li><a href="login.html" data-effect="mfp-move-from-top">Sign In</a>
                      </li>


                      <li class="dropdown">
                          <a class="fa fa-shopping-cart" href="shopping-cart.html"></a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>

        <div class="container">
            <header class="page-header">
                <h1 class="page-title"><%= @category.name %></h1>


            </header>
            <div class="row">

                <div class="col-md-12">
                    <div class="row" data-gutter="15">
                      <% @products.each do |product| %>
                        <div class="col-md-4">
                            <div class="product ">
                                <ul class="product-labels"></ul>
                                <div class="product-img-wrap">
                                    <img class="product-img-primary" src=<%= product.images[0].url %> alt="Image Alternative text" title="Image Title" />
                                </div>
                                <a class="product-link" href=<%= product_path(product.id) %>></a>
                                <div class="product-caption">
                                    <h5 class="product-caption-title"><%= product.name %></h5>
                                    <div class="product-caption-price"><span class="product-caption-price-new">
                                        <%= product.rent_price %>/-
                                    </div>
                                    <ul class="product-caption-feature-list">
                                        <li>Free Shipping</li>
                                    </ul>
                                </div>
                            </div>
                          </div>
                        <% end %>

                </div>
            </div>
        </div></div>

        <footer class="main-footer">
            <div class="container">
                <div class="row row-col-gap" data-gutter="60">
                    <div class="col-md-4">
                        <h4 class="widget-title-sm">TheBoomerang</h4>
                        <p>Tincidunt et scelerisque vulputate ultrices ante at eu risus tempor augue congue</p>
                        <ul class="main-footer-social-list">
                            <li>
                                <a class="fa fa-facebook" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-twitter" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-pinterest" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-instagram" href="product-layout-3.html#"></a>
                            </li>
                            <li>
                                <a class="fa fa-google-plus" href="product-layout-3.html#"></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h4 class="widget-title-sm">Popular Tags</h4>
                        <ul class="main-footer-tag-list">
                            <li><a href="product-layout-3.html#">New Season</a>
                            </li>
                            <li><a href="product-layout-3.html#">Watches</a>
                            </li>
                            <li><a href="product-layout-3.html#">woman</a>
                            </li>
                            <li><a href="product-layout-3.html#">classic</a>
                            </li>
                            <li><a href="product-layout-3.html#">modern</a>
                            </li>
                            <li><a href="product-layout-3.html#">blue</a>
                            </li>
                            <li><a href="product-layout-3.html#">shoes</a>
                            </li>
                            <li><a href="product-layout-3.html#">running</a>
                            </li>
                            <li><a href="product-layout-3.html#">jeans</a>
                            </li>
                            <li><a href="product-layout-3.html#">sports</a>
                            </li>
                            <li><a href="product-layout-3.html#">laptops</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h4 class="widget-title-sm">Jobs</h4>
                        <form>

                            <input class="btn btn-primary" type="submit" value="We're hiring" />
                        </form>
                    </div>
                </div>

            </div>
        </footer>

    </div>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/icheck.js"></script>
    <script src="js/ionrangeslider.js"></script>
    <script src="js/jqzoom.js"></script>
    <script src="js/card-payment.js"></script>
    <script src="js/owl-carousel.js"></script>
    <script src="js/magnific.js"></script>
    <script src="js/custom.js"></script>


    <script src="js/switcher.js"></script>



</body>

</html>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-sm-offset-2 col-md-offset-3">

    <h1 class='text-center'>Edit Product</h1>

    <%= simple_form_for(@product, html: { class: 'form-horizontal', multipart: true }) do |f| %>

      <%= f.input :name, required: false %>
      <%= f.input :rent_price %>
      <%= f.input :actual_price %>
      <%= f.input :sizes_available, collection: Product::SIZES, as: :check_boxes %>
      <%= f.association :categories, as: :check_boxes %>
      <%= f.input :description %>
      <%= f.input :images, as: :file, input_html: { multiple: true } %>

      <%= f.submit %>

    <% end %>


    <%= link_to 'All products', products_path %>

  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rent price</th>
      <th>Actual price</th>
      <th>Sizes available</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.rent_price %></td>
        <td><%= product.actual_price %></td>
        <td><%= product.sizes_available %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= button_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-sm-offset-2 col-md-offset-3">

    <h1 class='text-center'>New Product</h1>

    <%= simple_form_for(@product, html: { class: 'form-horizontal', multipart: true }) do |f| %>

      <%= f.input :name, required: false %>
      <%= f.input :rent_price %>
      <%= f.input :actual_price %>
      <%= f.input :sizes_available, collection: Product::SIZES, as: :check_boxes %>
      <%= f.association :categories, as: :check_boxes %>
      <%= f.input :description %>
      <%= f.input :images, as: :file, input_html: { multiple: true } %>

      <%= f.submit %>

    <% end %>


    <%= link_to 'All products', products_path %>

  </div>
</div>